version: "3.0"

services:

  app:
    build: ./app
    container_name: app
    volumes:
      - ./app:/usr/src/app
    tty: true
    networks:
      - app-network
    depends_on:
      - db  

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app     

networks:
  app-network:
    driver: bridge